### ISSUE TITLE
Переход на новый домен

### ISSUE THREAD

**Issue by AnatoliyCh** [ObiArt/megane#3]
В рамках оптимизации сайт [h-chan.me](https://h-chan.me/) переходит на новый домен [henchan.pro](https://henchan.pro/). 
Оригинальная новость: [Новая оптимизация от Хентай-тян](https://henchan.pro/news/32087-novaya-optimizaciya.html)

**Comment by AnatoliyCh** [comment]
А. ну собственно, после проверки (v 0.8.2 из магазина chrome) все равно есть необработанные картинки

**Comment by ObiArt** [comment]
Попробуй нажать Ctrl-F5, потому что у меня все работает
![image](https://user-images.githubusercontent.com/58375833/81829824-fe4c9280-9543-11ea-9a25-f95b1b148ce5.png)

**Comment by AnatoliyCh** [comment]
Ахах, это первым было сделано

**Comment by AnatoliyCh** [comment]
Кстати, **на стартовой работает**, но в самом каталоге нет.

**Comment by ObiArt** [comment]
Хах, так и есть... Исправлю

**Comment by AnatoliyCh** [comment]
Собственно старые версии норм подгружают:
![1](https://user-images.githubusercontent.com/18707515/81832178-64e3a780-9568-11ea-8c11-f9b250e095d8.PNG)
А вот новая версия даже не стартует:
![2](https://user-images.githubusercontent.com/18707515/81832211-6e6d0f80-9568-11ea-8bfa-1228964705d4.PNG)

**Comment by ObiArt** [comment]
Да... Честно, это такая нелепая ошибка, что я предпочту ее не обьяснять... Просто скажу, что обнова уже есть и залита на преверку в стор Opera и Chrome (Edge и Firefox все еще на версии 0.8.1, в которой этой ошибки нет)

**Comment by ObiArt** [comment]
Ладно, Chrome уже давно новую версию опубликовал, Opera совсем не хочет ее проверять, но ничего с этим я поделать не могу.
Баг исправлен.
